"""QA Test-Case Generator for the Benefit Engine.

Runs every scenario in scenarios.py through the actual Benefit Engine, captures
the expected result (or the expected rejection), and writes two artifacts:

  output/test_cases.md    a human-readable table for review
  output/test_cases.json  the same data as structured JSON, ready to drive tests

Because the Benefit Engine lives in a sibling folder whose name contains a hyphen
(benefit-formula-engine), it cannot be imported with a normal `import` statement.
The path shim below adds that folder to Python's import path so its modules become
importable. This is the one cross-tool link in the toolkit, and it is deliberate:
the QA cases are generated by the same code they are meant to verify.

Example
-------
    python generate_cases.py
    python generate_cases.py --out-dir ./output
"""

import argparse
import json
import os
import sys

# --- Path shim: make the Benefit Engine importable ------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
ENGINE_DIR = os.path.abspath(os.path.join(HERE, "..", "benefit-formula-engine"))
if ENGINE_DIR not in sys.path:
    sys.path.insert(0, ENGINE_DIR)
# --------------------------------------------------------------------------------

from plan_rules import DEFAULT_PLAN
from validators import (
    ValidationError,
    validate_salary_history,
    validate_years_of_service,
    validate_retirement_age,
)
from calculator import calculate_benefit

from scenarios import SCENARIOS


def run_scenario(scenario, rules):
    """Run one scenario through the engine and return a result dictionary.

    For a normal scenario the result carries the expected monthly payout. For a
    scenario marked expect_error, success means the engine raised a ValidationError;
    the result records the rejection message instead of a payout.
    """
    record = {
        "name": scenario["name"],
        "rationale": scenario["rationale"],
        "inputs": {
            "salaries": scenario["salaries"],
            "years_of_service": scenario["years_of_service"],
            "retirement_age": scenario["retirement_age"],
        },
        "expect_error": scenario["expect_error"],
    }

    try:
        salaries = validate_salary_history(scenario["salaries"], rules)
        credited, was_capped = validate_years_of_service(scenario["years_of_service"], rules)
        age = validate_retirement_age(scenario["retirement_age"], rules)
        result = calculate_benefit(salaries, credited, was_capped, age, rules)
    except ValidationError as error:
        record["outcome"] = "rejected"
        record["expected_monthly"] = None
        record["detail"] = str(error)
        record["passed"] = scenario["expect_error"] is True
        return record

    record["outcome"] = "calculated"
    record["expected_monthly"] = f"{result.monthly_payout:.2f}"
    record["detail"] = (
        f"FAE {result.final_average_earnings:.2f}, "
        f"service {result.credited_service}"
        f"{' (capped)' if result.service_was_capped else ''}, "
        f"net annual {result.net_annual:.2f}"
    )
    record["passed"] = scenario["expect_error"] is False
    return record


def generate(rules=DEFAULT_PLAN):
    """Run every scenario and return the list of result records."""
    return [run_scenario(scenario, rules) for scenario in SCENARIOS]


def to_markdown(records):
    """Render the result records as a markdown document."""
    header = (
        "| Scenario | Retirement age | Years of service | Expected monthly | Outcome | Why it matters |\n"
        "| --- | ---: | ---: | ---: | --- | --- |"
    )
    rows = []
    for record in records:
        monthly = record["expected_monthly"] if record["expected_monthly"] is not None else "rejected"
        rows.append(
            f"| {record['name']} "
            f"| {record['inputs']['retirement_age']} "
            f"| {record['inputs']['years_of_service']} "
            f"| {monthly} "
            f"| {record['outcome']} "
            f"| {record['rationale']} |"
        )
    table = "\n".join([header, *rows])
    return f"# Benefit Engine QA Test Cases\n\nGenerated by `generate_cases.py`. Do not edit by hand.\n\n{table}\n"


def write_artifacts(records, out_dir):
    """Write the markdown and JSON artifacts, creating the output folder if needed."""
    os.makedirs(out_dir, exist_ok=True)
    md_path = os.path.join(out_dir, "test_cases.md")
    json_path = os.path.join(out_dir, "test_cases.json")

    with open(md_path, "w", encoding="utf-8") as handle:
        handle.write(to_markdown(records))
    with open(json_path, "w", encoding="utf-8") as handle:
        json.dump(records, handle, indent=2)

    return md_path, json_path


def build_parser():
    parser = argparse.ArgumentParser(
        description="Generate QA test cases by running scenarios through the Benefit Engine."
    )
    parser.add_argument(
        "--out-dir",
        default=os.path.join(HERE, "output"),
        help="Folder to write test_cases.md and test_cases.json (default ./output).",
    )
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    records = generate()
    md_path, json_path = write_artifacts(records, args.out_dir)

    total = len(records)
    passed = sum(1 for record in records if record["passed"])
    print(f"Generated {total} QA test cases ({passed} of {total} behaved as expected).")
    for record in records:
        marker = "ok " if record["passed"] else "XX "
        monthly = record["expected_monthly"] or "rejected"
        print(f"  {marker}{record['name']}: {monthly}")
    print(f"\nWrote {md_path}")
    print(f"Wrote {json_path}")
    return 0 if passed == total else 1


if __name__ == "__main__":
    sys.exit(main())
